# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1fc384051f7b5e522c6f3fa50ac808d81dedb277aad00134f51236d17d89364fd9d881dbfc01be619264ab243e0bf89410a65a009d3c89ba58413f6c1d18fa

test:
  secret_key_base: f2e4f1da3e463e806e3c8b0239c95d0343844ec14f6294576a2f9fbde4f90a4202b399f12b9236f773cf55795ec303b593a563a162797101658359410a9addcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
